#Ubuntu VM created by Google compute engine
## https://docs.travis-ci.com/user/reference/overview/
dist: trusty

# If you need a more customizable environment running in a virtual machine :ubuntu environment
sudo: required

services:
 - docker

 #Specifies language
language: go

# language version
go:
- 1.8.1

install:
- bash scripts/install_dependencies.sh


before_script:
# creates executable file
- go build



jobs:
  include:
  #stage 1 to execute positive test case
    - stage: positive_testscripts
      script:
        - bash scripts/positive_testcases.sh

  # stage 2 to execute negative test case

    - stage: negative_testscripts
      script:
        - bash scripts/negative_testcases.sh

notifications:

  email:
    recipients:      
      - apurva.dhoble@click2cloud.net
  
    on_success: always
    on_failure: always


branches:
  only:
  - master

#to cache terraform installation directories
cache:
  directories:
    - ./usr/local/bin/


matrix:
# the build won’t be marked as finished until they have completed, use fast_finish to mark them as finish
    fast_finish: true
    allow_failures:
    - stage: negative_testscripts
